### ISSUE TITLE
onig 3.0.1  / onig_sys fails to build on windows

### ISSUE THREAD

**Issue by paul-tcell** [rust-onig/rust-onig#70]
There appears to be a difference in the onig 3.0.1 on crates.io and the 3.0.1 on git hub - the former has onig_sys 66.1.4 and the latter has onig_sys 67.0.0 which has a change in build.rs - I don't know if this is what's causing the build failure... but maybe?

```
error: failed to run custom build command for `onig_sys v66.1.4`
process didn't exit successfully: `C:\Gitlab\builds\.\0\y\x\target\debug\build\onig_sys-074ef9fa23663e81\build-script-build` (exit code: 101)
--- stderr

Microsoft (R) Program Maintenance Utility Version 14.12.25831.0
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.12.25827\bin\Hostx64\x64\cl.EXE"' : return code '0x2'
Stop.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("command [\"cmd\", \"/c\", \"C:\\\\Windows\\\\system32\\\\config\\\\systemprofile\\\\.cargo\\\\registry\\\\src\\\\github.com-1ecc6299db9ec823\\\\onig_sys-66.1.4\\\\make_win64.bat\"] exited with code 2") }) }', src\libcore\result.rs:906:4
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:91
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:380
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:397
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:577
   4: std::panicking::begin_panic<alloc::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:538
   5: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:522
   6: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:498
   7: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:71
   8: core::result::unwrap_failed<std::io::error::Error>
             at C:\projects\rust\src\libcore\macros.rs:23
   9: core::result::Result<alloc::string::String, std::io::error::Error>::unwrap<alloc::string::String,std::io::error::Error>
             at C:\projects\rust\src\libcore\result.rs:772
  10: build_script_build::compile
             at .\build.rs:102
  11: build_script_build::main
             at .\build.rs:120
  12: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:101
  13: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:51
  14: main
  15: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
  16: BaseThreadInitThunk

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by iwillspeak** [comment]
HI, Thanks for the issue. Are you trying to build this locally from a clone of this git repo? If so then the code appears to build successfully on Appveyor.

The current master branch is in the process of being updated to use the Oniguruma 6.7.0 release. Part of this update is the movement of the build customisations from `rust-onig` into the main Oniguruma repository. This is the reason that the `build.rs` file was changed.

From the above stack trace it looks like `CL` the windows 'compiler & linker' has failed for some reason. Unfortunately without more logging from the failed command it is difficult to work out why. I'll try and reproduce this locally.

**Comment by paul-tcell** [comment]
Hi,
It worked ok with the 1.6.1 version of onig.

I'm including onig as a crate dependency in my Cargo file:
```
[dependencies]
onig = "3.0.1"
```
I think it's saying `cmd /c C:\\\\Windows\\\\system32\\\\config\\\\systemprofile\\\\.cargo\\\\registry\\\\src\\\\github.com-1ecc6299db9ec823\\\\onig_sys-66.1.4\\\\make_win64.bat` exited with error 2.  That looks like file not found.

Our only windows machine is a headless CI builder, I'll try to get access and poke around.

Here is a trace with `RUST_BACKTRACE=full`:
```
$ cargo update
    Updating registry `https://github.com/rust-lang/crates.io-index`
$ cargo test
 Downloading hyper v0.11.14
   Compiling httparse v1.2.3
   Compiling crossbeam v0.3.2
   Compiling bitflags v1.0.1
   Compiling itoa v0.3.4
   Compiling pkg-config v0.3.9
   Compiling cfg-if v0.1.2
   Compiling slab v0.3.0
   Compiling winapi-build v0.1.1
   Compiling void v1.0.2
   Compiling log-mdc v0.1.0
   Compiling winapi v0.2.8
   Compiling jni-sys v0.3.0
   Compiling lazycell v0.6.0
   Compiling safemem v0.2.0
   Compiling dtoa v0.4.2
   Compiling cc v1.0.4
   Compiling quick-error v1.2.1
   Compiling byteorder v1.2.1
   Compiling lazy_static v1.0.0
   Compiling traitobject v0.1.0
   Compiling take v0.1.0
   Compiling smallvec v0.2.1
   Compiling version_check v0.1.3
   Compiling lazycell v0.5.1
   Compiling fnv v1.0.6
   Compiling linked-hash-map v0.5.0
   Compiling scoped-tls v0.1.0
   Compiling unicode-xid v0.0.4
   Compiling percent-encoding v1.0.1
   Compiling rustc-serialize v0.3.24
   Compiling antidote v1.0.0
   Compiling serde v1.0.27
   Compiling language-tags v0.2.2
   Compiling winapi v0.3.3
   Compiling libc v0.2.36
   Compiling quote v0.3.15
   Compiling gcc v0.3.54
   Compiling num-traits v0.1.41
   Compiling pest v0.4.1
   Compiling treebitmap v0.2.2
   Compiling futures v0.1.17
   Compiling lazy_static v0.2.11
   Compiling slab v0.4.0
   Compiling unreachable v0.1.1
   Compiling kernel32-sys v0.2.2
   Compiling ws2_32-sys v0.2.1
   Compiling miniz-sys v0.1.10
   Compiling humantime v1.0.0
   Compiling base64 v0.9.0
   Compiling unsafe-any v0.4.2
   Compiling unicase v2.1.0
   Compiling yaml-rust v0.4.0
   Compiling synom v0.11.3
   Compiling log v0.4.1
   Compiling erased-serde v0.3.3
   Compiling iovec v0.1.1
   Compiling num_cpus v1.8.0
   Compiling rand v0.3.20
   Compiling num-integer v0.1.35
   Compiling serde_json v1.0.9
   Compiling rust-crypto v0.2.36
   Compiling ordered-float v0.5.0
   Compiling relay v0.1.0
   Compiling tokio-service v0.1.0
   Compiling typemap v0.3.3
   Compiling syn v0.11.11
   Compiling log v0.3.9
   Compiling serde_yaml v0.7.3
   Compiling futures-cpupool v0.1.8
   Compiling bytes v0.4.6
   Compiling num-iter v0.1.34
   Compiling uuid v0.5.1
   Compiling serde-value v0.5.1
   Compiling serde_derive_internals v0.19.0
   Compiling tokio-io v0.1.4
   Compiling num v0.1.41
   Compiling os_pipe v0.6.0
   Compiling shared_child v0.3.2
   Compiling schannel v0.1.10
   Compiling winutil v0.1.1
   Compiling time v0.1.39
   Compiling flate2 v1.0.1
   Compiling net2 v0.2.31
   Compiling mime v0.3.5
   Compiling serde_derive v1.0.27
   Compiling duct v0.9.2
   Compiling hostname v0.1.4
   Compiling native-tls v0.1.5
   Compiling chrono v0.4.0
   Compiling miow v0.2.1
   Compiling onig_sys v66.1.4
   Compiling log4rs v0.8.0
   Compiling mio v0.6.12
error: failed to run custom build command for `onig_sys v66.1.4`
process didn't exit successfully: `C:\Gitlab\builds\a9f98505\0\y\x\target\debug\build\onig_sys-074ef9fa23663e81\build-script-build` (exit code: 101)
--- stderr

Microsoft (R) Program Maintenance Utility Version 14.12.25831.0
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.12.25827\bin\Hostx64\x64\cl.EXE"' : return code '0x2'
Stop.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("command [\"cmd\", \"/c\", \"C:\\\\Windows\\\\system32\\\\config\\\\systemprofile\\\\.cargo\\\\registry\\\\src\\\\github.com-1ecc6299db9ec823\\\\onig_sys-66.1.4\\\\make_win64.bat\"] exited with code 2") }) }', src\libcore\result.rs:906:4
stack backtrace:
   0:     0x7ff6bc8389a9 - std::sys_common::backtrace::_print
                               at C:\projects\rust\src\libstd\sys_common\backtrace.rs:91
   1:     0x7ff6bc843767 - std::panicking::default_hook::{{closure}}
                               at C:\projects\rust\src\libstd\panicking.rs:380
   2:     0x7ff6bc84343b - std::panicking::default_hook
                               at C:\projects\rust\src\libstd\panicking.rs:397
   3:     0x7ff6bc843dd1 - std::panicking::rust_panic_with_hook
                               at C:\projects\rust\src\libstd\panicking.rs:577
   4:     0x7ff6bc843c40 - std::panicking::begin_panic<alloc::string::String>
                               at C:\projects\rust\src\libstd\panicking.rs:538
   5:     0x7ff6bc843b21 - std::panicking::begin_panic_fmt
                               at C:\projects\rust\src\libstd\panicking.rs:522
   6:     0x7ff6bc843a94 - std::panicking::rust_begin_panic
                               at C:\projects\rust\src\libstd\panicking.rs:498
   7:     0x7ff6bc846b5e - core::panicking::panic_fmt
                               at C:\projects\rust\src\libcore\panicking.rs:71
   8:     0x7ff6bc7d7e39 - core::result::unwrap_failed<std::io::error::Error>
                               at C:\projects\rust\src\libcore\macros.rs:23
   9:     0x7ff6bc7d7a26 - core::result::Result<alloc::string::String, std::io::error::Error>::unwrap<alloc::string::String,std::io::error::Error>
                               at C:\projects\rust\src\libcore\result.rs:772
  10:     0x7ff6bc7d4047 - build_script_build::compile
                               at C:\Windows\system32\config\systemprofile\.cargo\registry\src\github.com-1ecc6299db9ec823\onig_sys-66.1.4\build.rs:102
  11:     0x7ff6bc7d44a1 - build_script_build::main
                               at C:\Windows\system32\config\systemprofile\.cargo\registry\src\github.com-1ecc6299db9ec823\onig_sys-66.1.4\build.rs:120
  12:     0x7ff6bc8448d1 - panic_unwind::__rust_maybe_catch_panic
                               at C:\projects\rust\src\libpanic_unwind\lib.rs:101
  13:     0x7ff6bc844071 - std::rt::lang_start
                               at C:\projects\rust\src\libstd\rt.rs:51
  14:     0x7ff6bc7d44d6 - main
  15:     0x7ff6bc84b11f - __scrt_common_main_seh
                               at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
  16:     0x7ffe25608363 - BaseThreadInitThunk

```

**Comment by iwillspeak** [comment]
If you look at the logging before that it appears that the reason `make_win64.bat` exited with code 2 was because `NMAKE` did. The reason `NMAKE` did was because `cl.exe` did, the Windows "compiler & linker".

**Comment by iwillspeak** [comment]
Could you try cloning and compiling [this gist](https://gist.github.com/iwillspeak/ba748d0c47fbd90b61148653fed81bef) please and see if that works? What is installed on your build machine? Visual Studio 2017, or just the native build tools? How do you set up the build environment before building (vcvars.bat and so on)?

**Comment by iwillspeak** [comment]
Hi, any update on this?

**Comment by paul-tcell** [comment]
Hi,  Sorry for the delay.   We finally got this to work on our environment by adding  a call to `vcvars.bat` before calling `cargo` on our project in our CI.   I wasn't able to try your gist, the way our build environment is it is all automated, can't really log in.   So probably we didn't have a path or something set that got set in vcvars.

**Comment by iwillspeak** [comment]
Ah, Ok. On Windows for MSVC Onig can only be compiled from the x64 or x86 developer tools command prompt. If not you'll have to use `vcvars` and/or `SetEnv` to prepare the environment. For reference [here's how it is done on our automated builds](https://github.com/rust-onig/rust-onig/blob/master/appveyor.yml#L127).
